default_agent: event_place_writer_reader
agents:
  event_place_writer_reader:
    name: event_place_writer_reader
    entrypoint: C:/Users/r.laface/Desktop/Codice/aws-agentcore/agents/event-place-writer/agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\r.laface\Desktop\Codice\aws-agentcore\agents\event-place-writer
    aws:
      execution_role: arn:aws:iam::879338784410:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-b884372072
      execution_role_auto_create: false
      account: '879338784410'
      region: us-east-1
      ecr_repository: 879338784410.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-event_place_writer_reader
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: event_place_writer_reader-2WQYqVFvzj
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:879338784410:runtime/event_place_writer_reader-2WQYqVFvzj
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-event_place_writer_reader-builder
      execution_role: arn:aws:iam::879338784410:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-b884372072
      source_bucket: bedrock-agentcore-codebuild-sources-879338784410-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: orchestrator_mem-SyV4bj45mc
      memory_arn: null
      memory_name: event_place_writer_reader_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
