default_agent: calculator
agents:
  calculator:
    name: calculator
    entrypoint: src/calculator_agent/agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::879338784410:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-ca7cc4362a
      execution_role_auto_create: false
      account: '879338784410'
      region: us-east-1
      ecr_repository: 879338784410.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-calculator-agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: calculator-lgV0vpGtcq
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:879338784410:runtime/calculator-lgV0vpGtcq
      agent_session_id: 96fcab22-87ae-4da6-88a3-7265602bc406
    codebuild:
      project_name: bedrock-agentcore-calculator-agent-builder
      execution_role: arn:aws:iam::879338784410:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-ca7cc4362a
      source_bucket: bedrock-agentcore-codebuild-sources-879338784410-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: CalculatorMemory20251212122204-p2dLdvHDBp
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:879338784410:memory/CalculatorMemory20251212122204-p2dLdvHDBp
      memory_name: CalculatorMemory20251212122204
      event_expiry_days: 90
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  calculator_agent:
    name: calculator_agent
    entrypoint: C:/Users/r.laface/Desktop/Codice/aws-agentcore/agents/calculator/src/calculator_agent/agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: C:\Users\r.laface\Desktop\Codice\aws-agentcore\agents\calculator\src\calculator_agent
    aws:
      execution_role: null
      execution_role_auto_create: true
      account: '879338784410'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: true
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: null
      memory_arn: null
      memory_name: calculator_agent_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
